**FOR ENGLISH TEXT-1:**

**IMPORTING THE MODULES:**

In [1]:
from nltk.corpus import stopwords #you can remove stop words for Speed
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx

**SPLITTING INTO SENTENCES:**

In [2]:
file = open("TEXT-1.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

ChatGPT, an AI designed to assist with a wide range of tasks
My primary function is to understand and generate human-like text based on the prompts I receive
I've been trained on a diverse dataset that includes books, articles, websites, and much more, allowing me to provide information, answer questions, generate creative content, and engage in conversations on a variety of topics
Essentially, I'm here to help you with whatever you need.


**PRINTING THE SENTENCES:**

In [3]:
print("Sentences are ", sentences)

Sentences are  [['ChatGPT,', 'an', 'AI', 'designed', 'to', 'assist', 'with', 'a', 'wide', 'range', 'of', 'tasks'], ['My', 'primary', 'function', 'is', 'to', 'understand', 'and', 'generate', 'human-like', 'text', 'based', 'on', 'the', 'prompts', 'I', 'receive'], ["I've", 'been', 'trained', 'on', 'a', 'diverse', 'dataset', 'that', 'includes', 'books,', 'articles,', 'websites,', 'and', 'much', 'more,', 'allowing', 'me', 'to', 'provide', 'information,', 'answer', 'questions,', 'generate', 'creative', 'content,', 'and', 'engage', 'in', 'conversations', 'on', 'a', 'variety', 'of', 'topics'], ['Essentially,', "I'm", 'here', 'to', 'help', 'you', 'with', 'whatever', 'you', 'need.']]


**BUILDING THE VECTOR FOR SENT1&2:**

In [4]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
   # build the vector for the first sentence
    for w in sent1:
        vector1[all_words.index(w)] += 1
    # build the vector for the second sentence
    for w in sent2:
        vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

**SIMILARITY MATRIX:**

In [5]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))

for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.         0.07216878 0.18257419 0.16666667]
 [0.07216878 0.         0.23717082 0.07216878]
 [0.18257419 0.23717082 0.         0.04564355]
 [0.16666667 0.07216878 0.04564355 0.        ]]


**SCORES IN SIMILARITY MATRIX:**

In [6]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph =nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.27016891494337747, 1: 0.2450355180000465, 2: 0.29267383593004126, 3: 0.1921217311265349}


**TOP RANKED SENTENCES:**

In [7]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.29267383593004126, ["I've", 'been', 'trained', 'on', 'a', 'diverse', 'dataset', 'that', 'includes', 'books,', 'articles,', 'websites,', 'and', 'much', 'more,', 'allowing', 'me', 'to', 'provide', 'information,', 'answer', 'questions,', 'generate', 'creative', 'content,', 'and', 'engage', 'in', 'conversations', 'on', 'a', 'variety', 'of', 'topics']), (0.27016891494337747, ['ChatGPT,', 'an', 'AI', 'designed', 'to', 'assist', 'with', 'a', 'wide', 'range', 'of', 'tasks']), (0.2450355180000465, ['My', 'primary', 'function', 'is', 'to', 'understand', 'and', 'generate', 'human-like', 'text', 'based', 'on', 'the', 'prompts', 'I', 'receive']), (0.1921217311265349, ['Essentially,', "I'm", 'here', 'to', 'help', 'you', 'with', 'whatever', 'you', 'need.'])]


**PICKING THREE SENTENCES:**

In [8]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=3
summarize_text = []
for i in range(n):
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 3


**SUMMERIZING THE TEXT:**

In [9]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 I've been trained on a diverse dataset that includes books, articles, websites, and much more, allowing me to provide information, answer questions, generate creative content, and engage in conversations on a variety of topics. ChatGPT, an AI designed to assist with a wide range of tasks. My primary function is to understand and generate human-like text based on the prompts I receive


**FOR TELUGU TEXT-2:**

**IMPORTING THE MODULES:**

In [10]:
from nltk.corpus import stopwords #you can remove stop words for Speed
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx

**SPLITTING INTO SENTENCES:**

In [11]:
file = open("TEXT-2.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

ChatGPT, విస్తృత శ్రేణి పనులలో సహాయం చేయడానికి రూపొందించబడిన AI
నేను స్వీకరించే ప్రాంప్ట్‌ల ఆధారంగా మనిషిని పోలిన వచనాన్ని అర్థం చేసుకోవడం మరియు రూపొందించడం నా ప్రాథమిక విధి
పుస్తకాలు, కథనాలు, వెబ్‌సైట్‌లు మరియు మరిన్నింటిని కలిగి ఉన్న విభిన్న డేటాసెట్‌పై నేను శిక్షణ పొందాను, సమాచారాన్ని అందించడానికి, ప్రశ్నలకు సమాధానం ఇవ్వడానికి, సృజనాత్మక కంటెంట్‌ను రూపొందించడానికి మరియు విభిన్న అంశాలపై సంభాషణలలో పాల్గొనడానికి నన్ను అనుమతిస్తుంది
ముఖ్యంగా, మీకు అవసరమైన వాటితో మీకు సహాయం చేయడానికి నేను ఇక్కడ ఉన్నాను.


**PRINTING THE SENTENCES:**

In [12]:
print("Sentences are ", sentences)

Sentences are  [['ChatGPT,', 'విస్తృత', 'శ్రేణి', 'పనులలో', 'సహాయం', 'చేయడానికి', 'రూపొందించబడిన', 'AI'], ['నేను', 'స్వీకరించే', 'ప్రాంప్ట్\u200cల', 'ఆధారంగా', 'మనిషిని', 'పోలిన', 'వచనాన్ని', 'అర్థం', 'చేసుకోవడం', 'మరియు', 'రూపొందించడం', 'నా', 'ప్రాథమిక', 'విధి'], ['పుస్తకాలు,', 'కథనాలు,', 'వెబ్\u200cసైట్\u200cలు', 'మరియు', 'మరిన్నింటిని', 'కలిగి', 'ఉన్న', 'విభిన్న', 'డేటాసెట్\u200cపై', 'నేను', 'శిక్షణ', 'పొందాను,', 'సమాచారాన్ని', 'అందించడానికి,', 'ప్రశ్నలకు', 'సమాధానం', 'ఇవ్వడానికి,', 'సృజనాత్మక', 'కంటెంట్\u200cను', 'రూపొందించడానికి', 'మరియు', 'విభిన్న', 'అంశాలపై', 'సంభాషణలలో', 'పాల్గొనడానికి', 'నన్ను', 'అనుమతిస్తుంది'], ['ముఖ్యంగా,', 'మీకు', 'అవసరమైన', 'వాటితో', 'మీకు', 'సహాయం', 'చేయడానికి', 'నేను', 'ఇక్కడ', 'ఉన్నాను.']]


**BUILDING THE VECTOR FOR SENT1&2:**

In [13]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
   # build the vector for the first sentence
    for w in sent1:
        vector1[all_words.index(w)] += 1
    # build the vector for the second sentence
    for w in sent2:
        vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

**SIMILARITY MATRIX:**

In [14]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))

for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.         0.         0.         0.20412415]
 [0.         0.         0.14400461 0.07715167]
 [0.         0.14400461 0.         0.05184758]
 [0.20412415 0.07715167 0.05184758 0.        ]]


**SCORES IN SIMILARITY MATRIX:**

In [15]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph =nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.21289610177103374, 1: 0.23708278321290502, 2: 0.2132691888774271, 3: 0.33675192613863414}


**TOP RANKED SENTENCES:**

In [16]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.33675192613863414, ['ముఖ్యంగా,', 'మీకు', 'అవసరమైన', 'వాటితో', 'మీకు', 'సహాయం', 'చేయడానికి', 'నేను', 'ఇక్కడ', 'ఉన్నాను.']), (0.23708278321290502, ['నేను', 'స్వీకరించే', 'ప్రాంప్ట్\u200cల', 'ఆధారంగా', 'మనిషిని', 'పోలిన', 'వచనాన్ని', 'అర్థం', 'చేసుకోవడం', 'మరియు', 'రూపొందించడం', 'నా', 'ప్రాథమిక', 'విధి']), (0.2132691888774271, ['పుస్తకాలు,', 'కథనాలు,', 'వెబ్\u200cసైట్\u200cలు', 'మరియు', 'మరిన్నింటిని', 'కలిగి', 'ఉన్న', 'విభిన్న', 'డేటాసెట్\u200cపై', 'నేను', 'శిక్షణ', 'పొందాను,', 'సమాచారాన్ని', 'అందించడానికి,', 'ప్రశ్నలకు', 'సమాధానం', 'ఇవ్వడానికి,', 'సృజనాత్మక', 'కంటెంట్\u200cను', 'రూపొందించడానికి', 'మరియు', 'విభిన్న', 'అంశాలపై', 'సంభాషణలలో', 'పాల్గొనడానికి', 'నన్ను', 'అనుమతిస్తుంది']), (0.21289610177103374, ['ChatGPT,', 'విస్తృత', 'శ్రేణి', 'పనులలో', 'సహాయం', 'చేయడానికి', 'రూపొందించబడిన', 'AI'])]


**PICKING THREE SENTENCES:**

In [17]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=3
summarize_text = []
for i in range(n):
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 3


**SUMMERIZING THE TEXT:**

In [18]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 ముఖ్యంగా, మీకు అవసరమైన వాటితో మీకు సహాయం చేయడానికి నేను ఇక్కడ ఉన్నాను.. నేను స్వీకరించే ప్రాంప్ట్‌ల ఆధారంగా మనిషిని పోలిన వచనాన్ని అర్థం చేసుకోవడం మరియు రూపొందించడం నా ప్రాథమిక విధి. పుస్తకాలు, కథనాలు, వెబ్‌సైట్‌లు మరియు మరిన్నింటిని కలిగి ఉన్న విభిన్న డేటాసెట్‌పై నేను శిక్షణ పొందాను, సమాచారాన్ని అందించడానికి, ప్రశ్నలకు సమాధానం ఇవ్వడానికి, సృజనాత్మక కంటెంట్‌ను రూపొందించడానికి మరియు విభిన్న అంశాలపై సంభాషణలలో పాల్గొనడానికి నన్ను అనుమతిస్తుంది


**FOR HINDI TEXT-3:**

**IMPORTING THE MODULES:**

In [19]:
from nltk.corpus import stopwords #you can remove stop words for Speed
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx

**SPLITTING INTO SENTENCES:**

In [20]:
file = open("TEXT-3.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

चैटजीपीटी, एक एआई जिसे कई प्रकार के कार्यों में सहायता के लिए डिज़ाइन किया गया है। मेरा प्राथमिक कार्य मुझे प्राप्त संकेतों के आधार पर मानव-सदृश पाठ को समझना और उत्पन्न करना है। मुझे एक विविध डेटासेट पर प्रशिक्षित किया गया है जिसमें किताबें, लेख, वेबसाइटें और बहुत कुछ शामिल है, जो मुझे जानकारी प्रदान करने, सवालों के जवाब देने, रचनात्मक सामग्री तैयार करने और विभिन्न विषयों पर बातचीत में शामिल होने की अनुमति देता है। मूलतः, मैं आपकी हर जरूरत में मदद करने के लिए यहां हूं।


**PRINTING THE SENTENCES:**

In [21]:
print("Sentences are ", sentences)

Sentences are  [['चैटजीपीटी,', 'एक', 'एआई', 'जिसे', 'कई', 'प्रकार', 'के', 'कार्यों', 'में', 'सहायता', 'के', 'लिए', 'डिज़ाइन', 'किया', 'गया', 'है।', 'मेरा', 'प्राथमिक', 'कार्य', 'मुझे', 'प्राप्त', 'संकेतों', 'के', 'आधार', 'पर', 'मानव-सदृश', 'पाठ', 'को', 'समझना', 'और', 'उत्पन्न', 'करना', 'है।', 'मुझे', 'एक', 'विविध', 'डेटासेट', 'पर', 'प्रशिक्षित', 'किया', 'गया', 'है', 'जिसमें', 'किताबें,', 'लेख,', 'वेबसाइटें', 'और', 'बहुत', 'कुछ', 'शामिल', 'है,', 'जो', 'मुझे', 'जानकारी', 'प्रदान', 'करने,', 'सवालों', 'के', 'जवाब', 'देने,', 'रचनात्मक', 'सामग्री', 'तैयार', 'करने', 'और', 'विभिन्न', 'विषयों', 'पर', 'बातचीत', 'में', 'शामिल', 'होने', 'की', 'अनुमति', 'देता', 'है।', 'मूलतः,', 'मैं', 'आपकी', 'हर', 'जरूरत', 'में', 'मदद', 'करने', 'के', 'लिए', 'यहां', 'हूं।']]


**BUILDING THE VECTOR OF SENT1&2:**

In [22]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
   # build the vector for the first sentence
    for w in sent1:
        vector1[all_words.index(w)] += 1
    # build the vector for the second sentence
    for w in sent2:
        vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

**SIMILARITY MATRIX:**

In [23]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))

for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.]]


**SCORES IN SIMILARITY MATRIX:**

In [24]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph =nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 1.0}


**TOP RANKED SENTENCES:**

In [25]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",ranked_sentence)

Indexes of top ranked_sentence order are 

 [(1.0, ['चैटजीपीटी,', 'एक', 'एआई', 'जिसे', 'कई', 'प्रकार', 'के', 'कार्यों', 'में', 'सहायता', 'के', 'लिए', 'डिज़ाइन', 'किया', 'गया', 'है।', 'मेरा', 'प्राथमिक', 'कार्य', 'मुझे', 'प्राप्त', 'संकेतों', 'के', 'आधार', 'पर', 'मानव-सदृश', 'पाठ', 'को', 'समझना', 'और', 'उत्पन्न', 'करना', 'है।', 'मुझे', 'एक', 'विविध', 'डेटासेट', 'पर', 'प्रशिक्षित', 'किया', 'गया', 'है', 'जिसमें', 'किताबें,', 'लेख,', 'वेबसाइटें', 'और', 'बहुत', 'कुछ', 'शामिल', 'है,', 'जो', 'मुझे', 'जानकारी', 'प्रदान', 'करने,', 'सवालों', 'के', 'जवाब', 'देने,', 'रचनात्मक', 'सामग्री', 'तैयार', 'करने', 'और', 'विभिन्न', 'विषयों', 'पर', 'बातचीत', 'में', 'शामिल', 'होने', 'की', 'अनुमति', 'देता', 'है।', 'मूलतः,', 'मैं', 'आपकी', 'हर', 'जरूरत', 'में', 'मदद', 'करने', 'के', 'लिए', 'यहां', 'हूं।'])]


**PICKKING ONE SENTENCE:**

In [30]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=1
summarize_text = []
for i in range(n):
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 1


**SUMMERIZING THE TEXT:**

In [31]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 चैटजीपीटी, एक एआई जिसे कई प्रकार के कार्यों में सहायता के लिए डिज़ाइन किया गया है। मेरा प्राथमिक कार्य मुझे प्राप्त संकेतों के आधार पर मानव-सदृश पाठ को समझना और उत्पन्न करना है। मुझे एक विविध डेटासेट पर प्रशिक्षित किया गया है जिसमें किताबें, लेख, वेबसाइटें और बहुत कुछ शामिल है, जो मुझे जानकारी प्रदान करने, सवालों के जवाब देने, रचनात्मक सामग्री तैयार करने और विभिन्न विषयों पर बातचीत में शामिल होने की अनुमति देता है। मूलतः, मैं आपकी हर जरूरत में मदद करने के लिए यहां हूं।
